/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Brand = IDL.Record({
  'id' : IDL.Nat32,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'logoUrl' : IDL.Text,
});
export const VirtualAssistantProvider = IDL.Record({
  'id' : IDL.Nat32,
  'paymentPerClient' : IDL.Nat32,
  'contactInfo' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
});

export const idlService = IDL.Service({
  'addBrand' : IDL.Func([IDL.Nat32, IDL.Text, IDL.Text, IDL.Text], [], []),
  'addProvider' : IDL.Func(
      [IDL.Nat32, IDL.Text, IDL.Text, IDL.Text, IDL.Nat32],
      [],
      [],
    ),
  'getAllBrands' : IDL.Func([], [IDL.Vec(Brand)], ['query']),
  'getProvidersSortedByPayment' : IDL.Func(
      [],
      [IDL.Vec(VirtualAssistantProvider)],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Brand = IDL.Record({
    'id' : IDL.Nat32,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'logoUrl' : IDL.Text,
  });
  const VirtualAssistantProvider = IDL.Record({
    'id' : IDL.Nat32,
    'paymentPerClient' : IDL.Nat32,
    'contactInfo' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  
  return IDL.Service({
    'addBrand' : IDL.Func([IDL.Nat32, IDL.Text, IDL.Text, IDL.Text], [], []),
    'addProvider' : IDL.Func(
        [IDL.Nat32, IDL.Text, IDL.Text, IDL.Text, IDL.Nat32],
        [],
        [],
      ),
    'getAllBrands' : IDL.Func([], [IDL.Vec(Brand)], ['query']),
    'getProvidersSortedByPayment' : IDL.Func(
        [],
        [IDL.Vec(VirtualAssistantProvider)],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };